name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y gcc g++ cmake lcov

    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./example_test

    - name: Generate coverage data
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' "${{ github.workspace }}/*googletest-src/*" --output-file coverage.info
        lcov --list coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./build/coverage.info
        fail_ci_if_error: true
